name: Weekly Playwright Regression

on:
  workflow_dispatch:

  schedule:
    # Every Monday at 09:00 UTC
    - cron: "0 9 * * 1"

jobs:
  regression:
    uses: ./.github/workflows/playwright.yml
    with:
      run_type: scheduled
    secrets: inherit